version: '3'

services:
  frontend:
    build: ./frontend
    container_name: frontend-receita
    tty: true
    stdin_open: true
    command: run dev
    restart: always
    working_dir: /app
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/tests:/app/tests
    ports:
      - 3000:3000
  backend-express:
    build: ./backend-express-ts
    container_name: api-receita-express
    tty: true
    stdin_open: true
    command: run dev
    restart: always
    working_dir: /app
    volumes:
      - ./backend-express-ts/src:/app/src
      - ./backend-express-ts/tests:/app/tests
    depends_on:
      database:
        condition: service_healthy
    ports:
      - 3001:3001
    environment:
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_HOST: ${DB_HOST}
      DATABASE_URL: ${DATABASE_URL}
      PORT: ${PORT}
      JWT_SECRET: ${JWT_SECRET}
  
  backend-nest:
    build: ./backend-nest-ts
    container_name: api-receita-nest
    tty: true
    stdin_open: true
    command: run start:dev
    restart: always
    working_dir: /app
    volumes:
      - ./backend-nest-ts/src:/app/src
      - ./backend-nest-ts/test:/app/test
    depends_on:
      database:
        condition: service_healthy
    ports:
      - 3001:3001
    environment:
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_PORT: ${DB_PORT}
      DB_HOST: ${DB_HOST}
      DATABASE_URL: ${DATABASE_URL}
      PORT: ${PORT}
      JWT_SECRET: ${JWT_SECRET}

  database:
    image: mysql:8.0.29
    container_name: receitas_db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DB_NAME: ${DB_NAME}
    ports:
      - 3306:3306
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"] # Deve aguardar o banco ficar operacional
    # volumes:
    #   - ./receitas.sql:/docker-entrypoint-initdb.d/receitas.sql
