version: '3'

services:
  frontend:
    image: node:18
    container_name: frontend-receita
    tty: true
    stdin_open: true
    command: npm run dev
    restart: always
    working_dir: /app
    volumes:
      - ./frontend/:/app
    depends_on:
      - backend
    ports:
      - 3000:3000
  backend:
    image: node:18
    container_name: api-receita
    tty: true
    stdin_open: true
    command: npm run dev
    restart: always
    working_dir: /home/node/app
    volumes:
      - ./backend/:/home/node/app
    depends_on:
      - database
    ports:
      - 3001:3001
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_PORT: ${MYSQL_PORT}
      MYSQL_HOST: ${MYSQL_HOST}
      PORT: ${PORT}
      JWT_SECRET: ${JWT_SECRET}
  
  database:
    image: mysql:8.0.29
    container_name: receitas_db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - 33060:3306
    # volumes:
    #   - ./receitas.sql:/docker-entrypoint-initdb.d/receitas.sql