version: '3'

services:
  frontend:
    image: node:18
    container_name: frontend-receita
    tty: true
    stdin_open: true
    command: npm run dev
    restart: always
    working_dir: /app
    volumes:
      - ./frontend/:/app
    depends_on:
      - backend
    ports:
      - 3000:3000
  backend:
    image: node:18
    container_name: api-receita
    tty: true
    stdin_open: true
    command: npm run dev
    restart: always
    working_dir: /home/node/app
    volumes:
      - ./backend/:/home/node/app
    depends_on:
      - database
    ports:
      - 3001:3001
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_PORT: 3306
      MYSQL_HOST: database
      PORT: 3001
  
  database:
    image: mysql:8.0.29
    container_name: receitas_db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: receitas_db
    ports:
      - 33060:3306
    volumes:
      - ./receitas.sql:/docker-entrypoint-initdb.d/receitas.sql